apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: cloudflare-tunnel-auth
  namespace: cloudflare-tunnel
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: read-cloudflare-tunnel
    serviceAccount: default