apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflare-secret-1
  namespace: cloudflare-tunnel
spec:
  type: kv-v2
  mount: kv
  path: cloudflare-tunnel/tunnel-1
  destination:
    name: tunnel-1-token
    create: true
    overwrite: false
  refreshAfter: 120s
  vaultAuthRef: cloudflare-tunnel-auth
  rolloutRestartTargets:
    - kind: Deployment
      name: cloudflare-tunnel-1
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflare-secret-2
  namespace: cloudflare-tunnel
spec:
  type: kv-v2
  mount: kv
  path: cloudflare-tunnel/tunnel-2
  destination:
    name: tunnel-2-token
    create: true
    overwrite: false
  refreshAfter: 120s
  vaultAuthRef: cloudflare-tunnel-auth
  rolloutRestartTargets:
    - kind: Deployment
      name: cloudflare-tunnel-2
