l2announcements:
  enabled: true
k8sClientRateLimit:
  qps: 10
  burst: 20
kubeProxyReplacement: true
ingressController:
  enabled: true
  loadbalancerMode: dedicated
loadBalancer:
  l7:
    backend: envoy
prometheus:
  enabled: true
operator:
  prometheus:
    enabled: true
hubble:
  # https://github.com/cilium/cilium/issues/20130
  tls:
    auto:
      enabled: true
      method: cronJob
      certValidityDuration: 1095
      schedule: "0 0 1 */4 *"
  relay:
    enabled: true
  ui:
    enabled: true
  metrics:
    enableOpenMetrics: true
    # 
    enabled:
      - dns:labelsContext=source_ip,source_namespace,source_workload,source_workload_kind,destination_ip,destination_namespace,destination_workload,destination_workload_kind,traffic_direction
      - drop:labelsContext=source_ip,source_namespace,source_workload,source_workload_kind,destination_ip,destination_namespace,destination_workload,destination_workload_kind,traffic_direction
      - tcp:labelsContext=source_ip,source_namespace,source_workload,source_workload_kind,destination_ip,destination_namespace,destination_workload,destination_workload_kind,traffic_direction
      - flow:labelsContext=source_ip,source_namespace,source_workload,source_workload_kind,destination_ip,destination_namespace,destination_workload,destination_workload_kind,traffic_direction
      - flows-to-world:labelsContext=source_ip,source_namespace,source_workload,source_workload_kind,destination_ip,destination_namespace,destination_workload,destination_workload_kind,traffic_direction
      - icmp:labelsContext=source_ip,source_namespace,source_workload,source_workload_kind,destination_ip,destination_namespace,destination_workload,destination_workload_kind,traffic_direction
      - httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,source_workload_kind,destination_ip,destination_namespace,destination_workload,destination_workload_kind,traffic_direction
