l2announcements:
  enabled: true
k8sClientRateLimit:
  qps: 10
  burst: 20
kubeProxyReplacement: true
ingressController:
  enabled: true
  loadbalancerMode: dedicated
loadBalancer:
  l7:
    backend: envoy
prometheus:
  enabled: true
operator:
  prometheus:
    enabled: true
hubble:
  relay:
    enabled: true
  ui:
    enabled: true
  metrics:
    enableOpenMetrics: true
    enabled:
      - dns
      - drop
      - tcp
      - flow
      - flows-to-world
      - icmp
