kubeProxyReplacement: true
prometheus:
  enabled: true
operator:
  prometheus:
    enabled: true
hubble:
  relay:
    enabled: true
  ui:
    enabled: true
  metrics:
    enableOpenMetrics: true
    enabled:
      - dns
      - drop:labelsContext=source_namespace,source_workload,destination_namespace,destination_workload,traffic_direction
      - tcp:labelsContext=source_namespace,source_workload,destination_namespace,destination_workload,traffic_direction
      - flow:sourceContext=workload|pod;destinationContext=workload|pod;labelsContext=source_namespace,source_workload,destination_namespace,destination_workload,traffic_direction
      - flows-to-world:sourceContext=dns|ip;destinationContext=dns|ip;labelsContext=source_namespace,source_workload,destination_namespace,destination_workload,traffic_direction
      - port-distribution:labelsContext=source_namespace,source_workload,destination_namespace,destination_workload,traffic_direction
      - icmp:labelsContext=source_namespace,source_workload,destination_namespace,destination_workload,traffic_direction
      - httpV2:exemplars=true;labelsContext=source_namespace,source_workload,destination_namespace,destination_workload,traffic_direction
