apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: step2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/tunamaguro/home-kubernetes-open.git
    targetRevision: main
    path: base-extensions/apps
  destination:
    server: "https://kubernetes.default.svc"