apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.rook.io/release
    chart: rook-ceph
    targetRevision: v1.15.1
    helm:
      valuesObject:
        csi:
          csiRBDProvisionerResource: |
            - name : csi-provisioner
              resource:
                requests:
                  memory: 64Mi
                  cpu: 50m
                limits:
                  memory: 128Mi
            - name : csi-resizer
              resource:
                requests:
                  memory: 64Mi
                  cpu: 50m
                limits:
                  memory: 128Mi
            - name : csi-attacher
              resource:
                requests:
                  memory: 64Mi
                  cpu: 50m
                limits:
                  memory: 128Mi
            - name : csi-snapshotter
              resource:
                requests:
                  memory: 64Mi
                  cpu: 50m
                limits:
                  memory: 128Mi
            - name : csi-rbdplugin
              resource:
                requests:
                  memory: 64Mi
                limits:
                  memory: 128Mi
            - name : csi-omap-generator
              resource:
                requests:
                  memory: 64Mi
                  cpu: 50m
                limits:
                  memory: 128Gi
            - name : liveness-prometheus
              resource:
                requests:
                  memory: 64Mi
                  cpu: 50m
                limits:
                  memory: 128Mi
          csiRBDPluginResource: |
            - name : driver-registrar
              resource:
                requests:
                  memory: 64Mi
                  cpu: 50m
                limits:
                  memory: 128Mi
            - name : csi-rbdplugin
              resource:
                requests:
                  memory: 64Mi
                  cpu: 50m
                limits:
                  memory: 128Mi
            - name : liveness-prometheus
              resource:
                requests:
                  memory: 64Mi
                  cpu: 50m
                limits:
                  memory: 128Mi
          csiCephFSProvisionerResource: |
            - name : csi-provisioner
              resource:
                requests:
                  memory: 64Mi
                  cpu: 50m
                limits:
                  memory: 128Mi
            - name : csi-resizer
              resource:
                requests:
                  memory: 64Mi
                  cpu: 50m
                limits:
                  memory: 128Mi
            - name : csi-attacher
              resource:
                requests:
                  memory: 64Mi
                  cpu: 50m
                limits:
                  memory: 128Mi
            - name : csi-snapshotter
              resource:
                requests:
                  memory: 64Mi
                  cpu: 50m
                limits:
                  memory: 128Mi
            - name : csi-cephfsplugin
              resource:
                requests:
                  memory: 64Mi
                  cpu: 50m
                limits:
                  memory: 128Mi
            - name : liveness-prometheus
              resource:
                requests:
                  memory: 64Mi
                  cpu: 50m
                limits:
                  memory: 128Mi 
          csiCephFSPluginResource: |
            - name : driver-registrar
              resource:
                requests:
                  memory: 64Mi
                  cpu: 50m
                limits:
                  memory: 128Mi
            - name : csi-cephfsplugin
              resource:
                requests:
                  memory: 64Mi
                  cpu: 50m
                limits:
                  memory: 128Mi
            - name : liveness-prometheus
              resource:
                requests:
                  memory: 64Mi
                  cpu: 50m
                limits:
                  memory: 128Mi
  destination:
    server: "https://kubernetes.default.svc"
    namespace: rook-ceph
  syncPolicy:
    # automated: 
    #   prune: true
    syncOptions:
      - CreateNamespace=true
