apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    targetRevision: 3.12.0 
    chart: metrics-server
    helm:
      valuesObject:
        args:
          # Nodeが本当にそのNodeかを検証しない
          - --kubelet-insecure-tls
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: metrics-server
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true