apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://operator.min.io
    chart: operator 
    targetRevision: 5.0.13
    helm:
      valuesObject:
        console:
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-production
            host: minio-operator.tunamaguro.work
            tls:
              - hosts:
                - minio-operator.tunamaguro.work
                secretName: minio-operator-ingress-tls
            path: /

  destination:
    server: "https://kubernetes.default.svc"
    namespace: minio-operator
  syncPolicy:
    automated: 
      prune: true
    syncOptions:
      - CreateNamespace=true
