apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.rook.io/release
    chart: rook-ceph
    targetRevision: v1.13.6
    helm:
      valuesObject:
        csiRBDProvisionerResource: |
          - name : csi-provisioner
            resource:
              requests:
                memory: 128Mi
                cpu: 50m
              limits:
                memory: 256Mi
          - name : csi-resizer
            resource:
              requests:
                memory: 128Mi
                cpu: 50m
              limits:
                memory: 256Mi
          - name : csi-attacher
            resource:
              requests:
                memory: 128Mi
                cpu: 50m
              limits:
                memory: 256Mi
          - name : csi-snapshotter
            resource:
              requests:
                memory: 128Mi
                cpu: 50m
              limits:
                memory: 256Mi
          - name : csi-rbdplugin
            resource:
              requests:
                memory: 128Mi
              limits:
                memory: 256Mi
          - name : csi-omap-generator
            resource:
              requests:
                memory: 128Mi
                cpu: 50m
              limits:
                memory: 256Gi
          - name : liveness-prometheus
            resource:
              requests:
                memory: 128Mi
                cpu: 50m
              limits:
                memory: 256Mi
        csiRBDPluginResource: |
          - name : driver-registrar
            resource:
              requests:
                memory: 128Mi
                cpu: 50m
              limits:
                memory: 256Mi
          - name : csi-rbdplugin
            resource:
              requests:
                memory: 128Mi
                cpu: 50m
              limits:
                memory: 256Mi
          - name : liveness-prometheus
            resource:
              requests:
                memory: 128Mi
                cpu: 50m
              limits:
                memory: 256Mi
        csiCephFSProvisionerResource: |
          - name : csi-provisioner
            resource:
              requests:
                memory: 128Mi
                cpu: 50m
              limits:
                memory: 256Mi
          - name : csi-resizer
            resource:
              requests:
                memory: 128Mi
                cpu: 50m
              limits:
                memory: 256Mi
          - name : csi-attacher
            resource:
              requests:
                memory: 128Mi
                cpu: 50m
              limits:
                memory: 256Mi
          - name : csi-snapshotter
            resource:
              requests:
                memory: 128Mi
                cpu: 50m
              limits:
                memory: 256Mi
          - name : csi-cephfsplugin
            resource:
              requests:
                memory: 128Mi
                cpu: 50m
              limits:
                memory: 256Mi
          - name : liveness-prometheus
            resource:
              requests:
                memory: 128Mi
                cpu: 50m
              limits:
                memory: 256Mi 
        csiCephFSPluginResource: |
            - name : driver-registrar
              resource:
                requests:
                  memory: 128Mi
                  cpu: 50m
                limits:
                  memory: 256Mi
            - name : csi-cephfsplugin
              resource:
                requests:
                  memory: 128Mi
                  cpu: 50m
                limits:
                  memory: 256Mi
            - name : liveness-prometheus
              resource:
                requests:
                  memory: 128Mi
                  cpu: 50m
                limits:
                  memory: 256Mi
  destination:
    server: "https://kubernetes.default.svc"
    namespace: rook-ceph
  syncPolicy:
    # automated: 
    #   prune: true
    syncOptions:
      - CreateNamespace=true
