apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-tunnel
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/tunamaguro/home-kubernetes-open.git
    path: base-extensions/cloudflare-tunnel
    targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cloudflare-tunnel
  syncPolicy:
    automated: 
      prune: true