apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflare-secret
  namespace: cert-manager
spec:
  type: kv-v2
  mount: kv
  path: cert-manager/cf-token
  destination:
    name: cloudflare-secret
    create: true
    overwrite: false
  refreshAfter: 120s
  vaultAuthRef: cert-manager-auth