apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: external-dns-auth
  namespace: external-dns
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: read-external-dns
    serviceAccount: default