apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflare-secret
  namespace: external-dns
spec:
  type: kv-v2
  mount: kv
  path: external-dns/cf-token
  destination:
    name: cloudflare-secret
    create: true
    overwrite: false
  refreshAfter: 120s
  vaultAuthRef: external-dns-auth
  rolloutRestartTargets:
    - kind: Deployment
      name: external-dns