apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vpa-admission-webhook
  namespace: kube-system
spec:
  secretName: vpa-tls-certs
  dnsNames:
    - vpa-webhook.kube-system.svc
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
